In [1]:
# csv 파일로 저장

import pandas as pd

data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }

df = pd.DataFrame(data)
df = df.set_index('name')

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [2]:
df.to_csv('./data/df_sample.csv')

In [2]:
# json 파일로 저장

import pandas as pd

data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }

df = pd.DataFrame(data)
df = df.set_index('name')

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [4]:
df.to_json('./data/df_sample.json')

In [5]:
df.to_json('./data/df_sample_split.json', orient='split')

In [6]:
df.to_json('./data/df_sample_index.json', orient='index')

In [7]:
df.to_json('./data/df_sample_columns.json', orient='columns')

In [3]:
df.to_json('./data/df_sample_columns.records', orient='records')

In [4]:
df.to_json('./data/df_sample_values.json', orient='values')